export const data = [
  {
    Date: "01.01.2019",
    Datasource: "Facebook Ads",
    Campaign: "Like Ads",
    Clicks: "274",
    Impressions: "1979",
  },
  {
    Date: "01.01.2019",
    Datasource: "Facebook Ads",
    Campaign: "Offer Campaigns - Conversions",
    Clicks: "10245",
    Impressions: "764627",
  },
  {
    Date: "01.01.2019",
    Datasource: "Google Adwords",
    Campaign: "B2B - Leads",
    Clicks: "7",
    Impressions: "444",
  },
  {
    Date: "01.01.2019",
    Datasource: "Google Adwords",
    Campaign: "GDN Prospecting - App - Prio 1 Offer",
    Clicks: "16",
    Impressions: "12535",
  },
  {
    Date: "01.01.2019",
    Datasource: "Google Adwords",
    Campaign: "GDN Prospecting - App - Prio 2 Offer",
    Clicks: "93",
    Impressions: "18866",
  },

  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Africa - Desktop",
    Clicks: "15",
    Impressions: "328",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Africa - Mobile",
    Clicks: "50",
    Impressions: "847",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Arab - Desktop",
    Clicks: "6",
    Impressions: "101",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Arab - Mobile",
    Clicks: "3",
    Impressions: "67",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Asia - Desktop",
    Clicks: "8",
    Impressions: "162",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Asia - Mobile",
    Clicks: "12",
    Impressions: "148",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - AUS - Desktop",
    Clicks: "24",
    Impressions: "1095",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Analytics",
    Campaign: "B2B - Leads",
    Clicks: "9",
    Impressions: "399",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Analytics",
    Campaign: "GDN Prospecting - App - Prio 1 Offer",
    Clicks: "26",
    Impressions: "12732",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Analytics",
    Campaign: "GDN Prospecting - Desktop - India Offer",
    Clicks: "86",
    Impressions: "65013",
  },
  {
    Date: "02.01.2019",
    Datasource: "Google Analytics",
    Campaign: "GDN Prospecting - Desktop - Prio 1 Offer",
    Clicks: "78",
    Impressions: "51448",
  },
  {
    Date: "03.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - GER - Desktop",
    Clicks: "36",
    Impressions: "1794",
  },
  {
    Date: "03.01.2019",
    Datasource: "Google Adwords",
    Campaign: "New General Campaign - Latin - Desktop",
    Clicks: "15",
    Impressions: "1392",
  },
  {
    Date: "03.01.2019",
    Datasource: "Google Analytics",
    Campaign: "B2B - Leads",
    Clicks: "10",
    Impressions: "425",
  },
  {
    Date: "03.01.2019",
    Datasource: "Google Analytics",
    Campaign: "GDN Prospecting - App - Prio 1 Offer",
    Clicks: "17",
    Impressions: "14068",
  },
  {
    Date: "03.01.2019",
    Datasource: "Google Analytics",
    Campaign: "GDN Prospecting - App - Prio 2 Offer",
    Clicks: "28",
    Impressions: "17654",
  },
];
